# Generated by Django 2.1.7 on 2019-02-25 13:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PatchContas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendas',
            old_name='data',
            new_name='parcela_um_data',
        ),
        migrations.RenameField(
            model_name='vendas',
            old_name='valor',
            new_name='parcela_um_val',
        ),
        migrations.RemoveField(
            model_name='vendas',
            name='parcelas',
        ),
        migrations.AddField(
            model_name='vendas',
            name='parcela_dois_data',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendas',
            name='parcela_dois_paga',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='vendas',
            name='parcela_dois_val',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='vendas',
            name='parcela_quatro_data',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendas',
            name='parcela_quatro_paga',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='vendas',
            name='parcela_quatro_val',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='vendas',
            name='parcela_tres_data',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendas',
            name='parcela_tres_paga',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='vendas',
            name='parcela_tres_val',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='vendas',
            name='parcela_um_paga',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='compras',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
